# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-quarkus
  annotations:
    "backstage.io/kubernetes-id": my-quarkus
spec:
  type: service
  lifecycle: experimental
  owner: guest