apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: toto
  annotations:
    backstage.io/kubernetes-id: toto
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ch007m/toto
    argocd/app-name: toto
spec:
  type: api
  lifecycle: production
  owner: user:default/guest